<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('账号开通申请'))?></h4>
            </div>
            <div class="modal-body">
                <img src="/ajax/gapper/auth/harbin/qrcode" />
                <div>
                    <a target="_blank" href="/ajax/gapper/auth/harbin/pdf"><?=H(T('确认'))?></a>
                    <button type="button" class="close" data-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>
</div>

