<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('账号开通申请'))?></h4>
            </div>
            <form class="modal-body form gapper-auth-form" method="POST" action="ajax/gapper/auth/harbin/register"><dl class="dl-horizontal">
                <dt class="text-center">
                    <div class="app-icon">
                        <div class="text-center app-icon-image"><img src="<?=H($icon)?>" /></div>
                        <div class="text-center app-icon-title"><?=H($type)?></div>
                    </div>
                </dt>
                <dd>
                    <div class="form-group">
                        <input class="form-control" type="text" name="username" placeholder="<?=H(T('卡号'))?>" />
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="<?=H(T('密码'))?>" />
                    </div>
                    <div class="form-group">
                        <input class="form-control btn btn-primary" type="submit" value="<?=H(T('提交'))?>"/>
                    </div>
                </dd>
            </dl></form>
        </div>
    </div>
</div>

